### ISSUE TITLE
Clear button doesn't reset map and filters

### ISSUE THREAD

**Issue by smit1678** [hotosm/OpenMapKitServer#44]

**Comment by willemarcel** [comment]
Did this error happen when running the `geojson-endpoint` branch? I fixed it with https://github.com/hotosm/OpenMapKitServer/commit/52f3489959a6e076a5e2a0ebee5ffe013f72ba81

**Comment by smit1678** [comment]
@willemarcel It seems to be resetting now for Device ID or username. But still doesn't work for date. 

There is also a new interaction, the filter button doesn't work at all now. The first time you click the clear button, then it filters. Second time you click the clear button then it resets the map and filters. 

![omk-filter-bug](https://user-images.githubusercontent.com/796838/44448708-31375000-a616-11e8-8e09-563956a84d05.gif)

**Comment by willemarcel** [comment]
Fixed with https://github.com/hotosm/OpenMapKitServer/commit/f41a80d7b4143df65ddf9b562993e5938b3d124f
